pyproject.toml, tests/mock/test_metadata.py
Updating test on package version to make it dynamic (previously it was static). This will be less error-prone :)
@drewm102 This test has already been applied in branch release/0.1 and is cherry-picked from it. It was necessary since we use that branch to create the new tag v0.1.0
=> FIX: update test package version to be dynamic

.github/workflows/ci_cd.yml, .github/workflows/template.yml, pyproject.toml
Release 0.1.1 got canceled because the wheelhouses were not built during CI.
This PR adds a job that will build the wheelhouses on top of performing smoke testing.
**Note**: Extra changes include :
- the project version to be 0.1.dev0 (should be the case in the main branch)
- the PR's template validation is extended to accept "CI:"
=> CI: add wheelhouse step

.github/workflows/ci_cd.yml
Having this here prevents outside contributors from running GH actions
=> FIX: remove private pypi index

README.rst
The doc links should have been updated at the time of public release to point to the stable doc. I created this PR to update them.
=> DOC: Update doc links in README to point to the stable doc.

src/ansys/edb/core/primitive/primitive.py
=> FIX: Padstack possition on constructor

src/ansys/edb/core/session.py
Fix the check of the server's stdout output when determining if the server has started or not.
Fixes #369
=> FIX: check for launched server session

src/ansys/edb/core/inner/messages.py
Issue:
- ProductIdType was passed directly as enum to protobuf message and causing errors on EdgeTerminal.get_product_solver_names
Changes:
- Pass underlying int to protobuf message
fix: #383
=> FIX: edge terminal product type

src/ansys/edb/core/session.py
=> FEATURE: Checking for port used before starting server session

pyproject.toml, src/ansys/edb/core/definition/padstack_def_data.py
=> FEATURE: Add GetConnectionPt SetConnectionPt API in PadstackDefData

pyproject.toml, src/ansys/edb/core/edb_defs.py, src/ansys/edb/core/hierarchy/inst_array.py
=> FEATURE: Set LayoutObjType of InstArray to CELL_INSTANCE

pyproject.toml, src/ansys/edb/core/layout/layout.py
=> FEATURE: Add support for layer based geometry pre-processing

.github/workflows/ci_cd.yml, AUTHORS, CONTRIBUTORS.md, doc/.vale.ini, doc/styles/Vocab/ANSYS/accept.txt, pyproject.toml, src/ansys/edb/core/hierarchy/pin_group.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/simulation_setup/simulation_setup.py, src/ansys/edb/core/simulation_setup/siwave_simulation_settings.py, src/ansys/edb/core/terminal/terminals.py
closes #417, closes #431, closes #434, closes #429, closes #427, closes #426, closes #418, closes #414
=> FIX: Miscellaneous fixes

src/ansys/edb/core/simulation_setup/simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_setup.py, tests/e2e/scratch/sim_setup_scratch.py
closes #305, removes remaining enforce_dc_and_causality refs
=> FIX: Fixed lambda typo, removed remaining enforce_dc_and_causality refs

AUTHORS, CONTRIBUTORS.md, doc/.vale.ini, doc/styles/Vocab/ANSYS/accept.txt, pyproject.toml, src/ansys/edb/core/hierarchy/pin_group.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/layout/layout.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_setup.py, src/ansys/edb/core/simulation_setup/siwave_simulation_settings.py, src/ansys/edb/core/terminal/terminals.py, tests/e2e/scratch/sim_setup_scratch.py
includes changes from #424, #436, #437
=> Publish pyedb-core v0.1.8

src/ansys/edb/core/layout/layout.py
=> FEATURE: Add mesh region support

src/ansys/edb/core/geometry/polygon_data.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/primitive/primitive.py
closes #454 , closes #455, closes #456, closes #460, closes #461
=> FIX: Fix diff pair and polygon data bugs

doc/source/api/geometry.rst, src/ansys/edb/core/geometry/polygon_data.py
=> FIX: Fix PolygonData intersection_type API

src/ansys/edb/core/session.py, tests/e2e/unit_tests/test_session.py
Add a function `_find_available_port` to find a port in the range [50051, 60000] that is available to open a listening socket on.  Use this function to automatically select a port when either `launch_session` or `session` are used to launch a gRPC server session
and `port_num` is `None` (the default).
Closes #478
=> FEATURE: Auto select server port

pyproject.toml, src/ansys/edb/core/inner/base.py, src/ansys/edb/core/inner/conn_obj.py, src/ansys/edb/core/inner/factory.py, src/ansys/edb/core/inner/interceptors.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/inner/utils.py, src/ansys/edb/core/layout/layout.py, src/ansys/edb/core/net/net.py, src/ansys/edb/core/session.py, src/ansys/edb/core/utility/cache.py
=> FEATURE: Add client side caching and pre-loading support

pyproject.toml, src/ansys/edb/core/inner/rpc_info.py
Removed write_no_cache_invalidation where necessary to avoid stale cache. This fixes the remaining failing pyedb unit tests.
=> FIX: Removed write_no_cache_invalidation where necessary to avoid stale cache

src/ansys/edb/core/net/net.py
=> FIX: Net.extended_net returns first ExtendedNet object

src/ansys/edb/core/primitive/primitive_instance_collection.py
Change `PointLike` to `Point2DLike` to correct broken term link in `PrimitiveInstanceCollection` class
=> FIX: Fix prim inst doc build failure

src/ansys/edb/core/simulation_setup/simulation_setup.py
Removes the deprecated `SweepData.frequencies` attribute. The frequency sweep frequencies are specified using the `SweepData.start_f`, `SweepData.end_f`, `SweepData.distribution`, and `SweepData.step` attributes
=> FIX: Remove deprecated frequencies attribute to fix unit tests

doc/source/api/simulation_setup.rst, src/ansys/edb/core/simulation_setup/simulation_setup.py, tests/e2e/integration_tests/test_spiral_inductor.py
=> FEATURE: Add support for multiple frequencies in a frequency sweep

doc/source/api/glossary.rst, src/ansys/edb/core/definition/dataset_def.py, src/ansys/edb/core/definition/debye_model.py, src/ansys/edb/core/definition/die_property.py, src/ansys/edb/core/definition/dielectric_material_model.py, src/ansys/edb/core/definition/djordjecvic_sarkar_model.py, src/ansys/edb/core/definition/ic_component_property.py, src/ansys/edb/core/definition/io_component_property.py, src/ansys/edb/core/definition/material_def.py
Fixes of documentation for the following modules:
- dataset_def.py
- debye_model.py
- die_property.py
- dielectric_material_model.py
- djordjecvic_sarkar_model.py
- ic_component_property.py
- io_component_property.py
- material_def.py
=> DOC: Fix up definition module docs Part 1

src/ansys/edb/core/terminal/edge_terminal.py, tests/e2e/conftest.py, tests/e2e/unit_tests/test_edge_terminal.py
Debugging revealed that the upstream API is returning a structure with a typo in an attribute name (i.e. `primitve_params` instead of `primitive_params`).  For now patch the client to look for this name.
Fixes #616
=> FIX: Fix PrimitiveEdge primitive property getter
