.github/workflows/ci_cd.yml, doc/Makefile, doc/make.bat, doc/source/conf.py, pyproject.toml, src/ansys/edb/core/database.py, src/ansys/edb/core/definition/bondwire_def.py, src/ansys/edb/core/definition/die_property.py, src/ansys/edb/core/definition/dielectric_material_model.py, src/ansys/edb/core/definition/material_def.py, src/ansys/edb/core/definition/padstack_def_data.py, src/ansys/edb/core/edb_defs.py, src/ansys/edb/core/geometry/arc_data.py, src/ansys/edb/core/geometry/polygon_data.py, src/ansys/edb/core/hierarchy/component_group.py, src/ansys/edb/core/hierarchy/structure3d.py, src/ansys/edb/core/layer/layer.py, src/ansys/edb/core/layer/layer_collection.py, src/ansys/edb/core/layer/stackup_layer.py, src/ansys/edb/core/layout/cell.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/simulation_setup/hfss_simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_setup.py, src/ansys/edb/core/simulation_setup/siwave_simulation_settings.py, src/ansys/edb/core/utility/heat_sink.py, src/ansys/edb/core/utility/hfss_extent_info.py
@hiro727 @drewm102 This PR should make things back on track and allow you to make a new release through a new tag. Contrary to the previous one that was performed by hand (as no pdf file was uploaded) the resulting release should be available from github with many artifacts.
We can discuss on that next week if you want :)
=> DOC: Generate pdf documentation in CI

pyproject.toml
Use version 0.2.dev0 instead of 0.1.dev0.
=> FIX: update version metadata

AUTHORS
=> FIX: follow pyansys repo guidelines

src/ansys/edb/core/hierarchy/pin_group.py
=> FIX: PinGroup inheritance

src/ansys/edb/core/simulation_setup/raptor_x_simulation_settings.py
Removing depreciated ArcResolution setting from RaptorX solution setups
=> FEATURE: Removing depreciated ArcResolution setting from RaptorX solution setups

src/ansys/edb/core/layout/cell.py
Changes:
- Add cell.suppressed_pads getter and setter
Note:
- no proto file changes
fix #331
=> FEATURE: Allow suppression of pads

doc/source/api/glossary.rst, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/terminal/terminals.py, tests/mock/test_terminals.py
resolves #314 
Changes:
- product_solver methods
- fix .terminals
- fix .edges
- fix docstring cross references
=> FIX: Fix terminal methods

src/ansys/edb/core/definition/component_def.py, src/ansys/edb/core/inner/messages.py
=> FEATURE: Support null footprints from component def

doc/source/api/simulation_setup.rst, doc/source/conf.py, pyproject.toml, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/simulation_setup/__init__.py, src/ansys/edb/core/simulation_setup/hfss_simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_setup.py, tests/e2e/integration_tests/test_spiral_inductor.py
Closes #322 #324 #321 #320 #319 #310 #308 #307 #306 #304
=> FIX: Added missing sim setup APIs

doc/source/api/simulation_setup.rst, doc/source/conf.py, pyproject.toml, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/simulation_setup/__init__.py, src/ansys/edb/core/simulation_setup/hfss_simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_setup.py, tests/e2e/integration_tests/test_spiral_inductor.py
Publish pyedb-core package v0.1.4. Cherry picked over changes from the #378
=> Publish pyedb-core v0.1.4

src/ansys/edb/core/hierarchy/hierarchy_obj.py, src/ansys/edb/core/primitive/primitive.py
These changes were merged in Nov 2023, but went missing during the repo migration to ansys-api-edb.
fix #382 
fix #292
=> FIX: Add Path.polygon_data and fix Component transform

src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/simulation_setup/simulation_settings.py
=> FIX: Fixed num_via_sides setter msg type

doc/source/api/hierarchy.rst, pyproject.toml, src/ansys/edb/core/hierarchy/layout_component.py, src/ansys/edb/core/session.py
=> FEATURE: Added layout component support

doc/source/api/hierarchy.rst, pyproject.toml, src/ansys/edb/core/hierarchy/layout_component.py, src/ansys/edb/core/session.py
Contains changes from the following PRs:
#410 
#406
=> Publish pyedb-core v0.1.6

doc/source/api/simulation_setup.rst, pyproject.toml, src/ansys/edb/core/simulation_setup/simulation_settings.py
=> FEATURE: Add model_type in AdvancedSettings

doc/source/api/simulation_setup.rst, pyproject.toml, src/ansys/edb/core/simulation_setup/simulation_settings.py
Contains changes from the following PRs:
#416
=> Publish pyedb-core v0.1.7

.github/workflows/ci_cd.yml, pyproject.toml, src/ansys/edb/core/geometry/polygon_data.py, src/ansys/edb/core/hierarchy/component_group.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/layout/layout.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, tests/e2e/scratch/sim_setup_scratch.py
closes #443, closes #439, closes #447, closes #448, closes #449, closes #451
=> FEATURE: Add support for via plating meshing, miscellaneous fixes

.github/workflows/ci_cd.yml, pyproject.toml, src/ansys/edb/core/geometry/polygon_data.py, src/ansys/edb/core/hierarchy/component_group.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/layout/layout.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, tests/e2e/scratch/sim_setup_scratch.py
Contains changes from #446 , #453 , #459
=> Publish pyedb-core v0.1.9

CONTRIBUTORS.md
=> FIX: format alignment for CONTRIBUTORS.md

pyproject.toml, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/layout/layout.py
=> FEATURE: Add support for applying primitive snapping to multiple layers

pyproject.toml, src/ansys/edb/core/database.py, src/ansys/edb/core/definition/component_def.py, src/ansys/edb/core/definition/debye_model.py, src/ansys/edb/core/inner/interceptors.py, src/ansys/edb/core/inner/variable_server.py, src/ansys/edb/core/layout/cell.py, src/ansys/edb/core/layout/layout.py, src/ansys/edb/core/simulation_setup/hfss_simulation_settings.py, src/ansys/edb/core/simulation_setup/raptor_x_simulation_settings.py, src/ansys/edb/core/simulation_setup/simulation_settings.py, src/ansys/edb/core/utility/io_manager.py
=> FIX: Miscellaneous IOManager related fixes

doc/source/api/glossary.rst, doc/source/api/primitive.rst, pyproject.toml, src/ansys/edb/core/inner/factory.py, src/ansys/edb/core/inner/parser.py, src/ansys/edb/core/inner/rpc_info.py, src/ansys/edb/core/inner/utils.py, src/ansys/edb/core/layout/layout.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/primitive/primitive_instance_collection.py, src/ansys/edb/core/session.py, src/ansys/edb/core/typing/__init__.py
=> FEATURE: Added primitive instance collection support

doc/source/api/utility.rst, pyproject.toml, src/ansys/edb/core/geometry/polygon_data.py, src/ansys/edb/core/hierarchy/spice_model.py, src/ansys/edb/core/inner/factory.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/inner/parser.py, src/ansys/edb/core/inner/rpc_info.py, src/ansys/edb/core/inner/utils.py, src/ansys/edb/core/layout_instance/layout_instance.py, src/ansys/edb/core/primitive/primitive_instance_collection.py, src/ansys/edb/core/session.py, src/ansys/edb/core/utility/edb_error_manager.py, src/ansys/edb/core/utility/io_manager.py
=> FEATURE: Added support for EDB error manager and other miscellaneous 25.2 fixes

pyproject.toml, src/ansys/edb/core/definition/component_def.py, src/ansys/edb/core/inner/messages.py, src/ansys/edb/core/inner/rpc_info.py
=> FIX: Add missing comp def APIs

doc/source/api/primitive.rst, src/ansys/edb/core/inner/conn_obj.py, src/ansys/edb/core/inner/layout_obj.py, src/ansys/edb/core/primitive/board_bend_def.py, src/ansys/edb/core/primitive/bondwire.py, src/ansys/edb/core/primitive/circle.py, src/ansys/edb/core/primitive/padstack_instance.py, src/ansys/edb/core/primitive/path.py, src/ansys/edb/core/primitive/polygon.py, src/ansys/edb/core/primitive/primitive.py, src/ansys/edb/core/primitive/primitive_instance_collection.py, src/ansys/edb/core/primitive/rectangle.py, src/ansys/edb/core/primitive/text.py
=> FIX: Fix primitive doc

.github/workflows/ci_cd.yml, tox.ini
Update python versions in ci_cd.yml so the minimum version is 3.10
=> FIX: Update python versions in ci_cd.yml

src/ansys/edb/core/primitive/padstack_instance.py
=> FIX: Circular import error when importing PadstackInstance

pyproject.toml, src/ansys/edb/core/definition/io_component_property.py
Fixes port_property import that was broken in #534. Also bump pre-release pkg version.
=> DOC: Fix port_property import. Also bump pre-release pkg version.

.github/workflows/ci_cd.yml
(cherry picked from commit 0772bc46d2d9ce12421e36c86d2ce37ed3a5e3e1)
=> FIX: fix typo in runner name (#586)

doc/source/api/definition.rst, doc/source/api/glossary.rst, src/ansys/edb/core/definition/bondwire_def.py, src/ansys/edb/core/definition/component_def.py, src/ansys/edb/core/definition/component_model.py, src/ansys/edb/core/definition/component_pin.py, src/ansys/edb/core/definition/component_property.py, src/ansys/edb/core/definition/dataset_def.py, src/ansys/edb/core/definition/material_def.py, src/ansys/edb/core/definition/material_property_thermal_modifier.py, src/ansys/edb/core/definition/multipole_debye_model.py, src/ansys/edb/core/definition/package_def.py, src/ansys/edb/core/definition/padstack_def.py, src/ansys/edb/core/definition/padstack_def_data.py, src/ansys/edb/core/definition/port_property.py, src/ansys/edb/core/definition/rlc_component_property.py, src/ansys/edb/core/definition/solder_ball_property.py
Fixes up second part of definition class documentation as described in #511
=> DOC: Definition documentation update part 2

src/ansys/edb/core/geometry/polygon_data.py
=> FIX: PolygonData.normalized is failing
